### PR TITLE
Make it possible to install cl-brewer from Homebrew tap and more!

### PR DESCRIPTION
**Pull request by svetlyak40wt**
Also, some features were added, like:

* support for preloading some systems before the build.
* support for creating formulas for systems which use [Deploy](https://github.com/Shinmera/deploy) instead of ``buildapp`.
* compression support when using buildapp.
* support of package inferred systems.

Also issue https://github.com/can3p/cl-brewer/issues/1 was solved.

### CODE REVIEW

**Comment by can3p** [comment]
@svetlyak40wt Sorry for the super late reaction. I'm not working on cl-brewer actively anymore. I can transfer the ownership to you or move the repo to 40ants org if you like

**Comment by svetlyak40wt** [comment]
Move to 40ants would be cool!

I really want to make CL utilities installation on OSX easy and transparent to users who unaware of CL.

**Comment by can3p** [comment]
Just tried it, can't create public repos on 40ants. I can transfer it to your account, although you might need to remove the fork first

**Comment by svetlyak40wt** [comment]
Done, I've removed my fork.

**Comment by can3p** [comment]
I've initiated the transfer

**Pull request merged**
